//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHome.HomeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HomeService.ISmartHomeService")]
    public interface ISmartHomeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartHomeService/MakeAction", ReplyAction="http://tempuri.org/ISmartHomeService/MakeActionResponse")]
        string[] MakeAction(string[] ID, string type, string Action, string Parametr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartHomeService/MakeAction", ReplyAction="http://tempuri.org/ISmartHomeService/MakeActionResponse")]
        System.Threading.Tasks.Task<string[]> MakeActionAsync(string[] ID, string type, string Action, string Parametr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmartHomeServiceChannel : SmartHome.HomeService.ISmartHomeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmartHomeServiceClient : System.ServiceModel.ClientBase<SmartHome.HomeService.ISmartHomeService>, SmartHome.HomeService.ISmartHomeService {
        
        public SmartHomeServiceClient() {
        }
        
        public SmartHomeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmartHomeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartHomeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartHomeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] MakeAction(string[] ID, string type, string Action, string Parametr) {
            return base.Channel.MakeAction(ID, type, Action, Parametr);
        }
        
        public System.Threading.Tasks.Task<string[]> MakeActionAsync(string[] ID, string type, string Action, string Parametr) {
            return base.Channel.MakeActionAsync(ID, type, Action, Parametr);
        }
    }
}
